version: '3'

networks:
  default:

services:
  tempcalc:
    build:
      context: .
      dockerfile: ./tempCalc/Dockerfile
    volumes:
      - ./tempCalc:/tempCalc
    networks:
      - default
    tty: true
    ports:
      - 5000:5000

