# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'HGCircularSlider', '~> 2.0.0'
pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON'

target 'hACk_client' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hACk_client

end
